const $=id=>document.getElementById(id), subjects=['Software Engineering','Operating System','Advanced Computer'];let activeSubject='Operating System',activeLesson='Unit 1',library={},timer;
const blank=(s,l)=>({title:`${s} — ${l}`,section:'Introduction',notes:'Start writing your lesson notes here.',facts:[],sections:[],images:[]});
function seed(){try{library=JSON.parse(localStorage.getItem('samarth-vault'))||{}}catch{}subjects.forEach(s=>{library[s]??={};library[s]['Unit 1']??=blank(s,'Unit 1')});}
function draft(){return library[activeSubject][activeLesson]}
function saveLocal(){localStorage.setItem('samarth-vault',JSON.stringify(library));clearTimeout(timer);timer=setTimeout(saveCloud,1200)}
function auth(){const token=sessionStorage.getItem('vault-token');return token?{Authorization:`Bearer ${token}`}:{};}
async function saveCloud(){if(!sessionStorage.getItem('vault-token'))return;try{const r=await fetch('/api/drafts/samarthp2727',{method:'PUT',headers:{...auth(),'Content-Type':'application/json'},body:JSON.stringify({library,activeSubject,activeLesson})});$('cloudState').textContent=r.ok?'Saved permanently to TiDB':'Cloud save failed';}catch{$('cloudState').textContent='Saved in this browser';}}
async function loadCloud(){try{const r=await fetch('/api/drafts/samarthp2727',{headers:auth()});if(!r.ok)return;const data=(await r.json()).draft;if(data.library){library=data.library;activeSubject=data.activeSubject||activeSubject;activeLesson=data.activeLesson||activeLesson;saveLocal();}}catch{}}
function showDashboard(){ $('dashboard').hidden=false;$('reader').hidden=true;$('editor').hidden=true;const cards=$('subjectCards');cards.innerHTML=subjects.map(s=>`<button class="card" data-subject="${s}"><p>${Object.keys(library[s]).length} LESSONS</p><h2>${s}</h2><span>Open every saved lesson in a focused reading view.</span><b>Open notes →</b></button>`).join('');cards.querySelectorAll('button').forEach(b=>b.onclick=()=>{activeSubject=b.dataset.subject;activeLesson=Object.keys(library[activeSubject])[0];showReader();});}
function showReader(){const d=draft();$('dashboard').hidden=true;$('reader').hidden=false;$('editor').hidden=true;$('subjectName').textContent=activeSubject.toUpperCase();$('lessonSelect').innerHTML=Object.keys(library[activeSubject]).map(l=>`<option ${l===activeLesson?'selected':''}>${l}</option>`).join('');$('crumb').textContent=`${activeSubject.toUpperCase()} · ${activeLesson.toUpperCase()}`;$('titleView').textContent=d.title;$('sectionView').textContent=d.section;$('notesView').textContent=d.notes;$('factsView').innerHTML=d.facts.map(x=>`<li>${escape(x)}</li>`).join('');$('extraView').innerHTML=d.sections.map((s,i)=>`<section class="extra"><h3>${escape(s.heading)}</h3><div class="notes">${escape(s.notes)}</div></section>`).join('');$('imagesView').innerHTML=d.images.map(src=>`<img src="${src}" alt="Lesson reference">`).join('');}
function escape(s=''){const d=document.createElement('div');d.textContent=s;return d.innerHTML;}
function showEditor(){const d=draft();$('editor').hidden=false;$('titleInput').value=d.title;$('sectionInput').value=d.section;$('notesInput').value=d.notes;$('factsInput').value=d.facts.join('\n');renderSectionEditor();}
function renderSectionEditor(){const holder=$('sectionEditor');holder.innerHTML=draft().sections.map((s,i)=>`<div class="section-edit"><input data-i="${i}" data-k="heading" value="${escape(s.heading)}"><textarea data-i="${i}" data-k="notes" rows="4">${escape(s.notes)}</textarea><button data-remove="${i}">Remove</button></div>`).join('');holder.querySelectorAll('input,textarea').forEach(el=>el.oninput=()=>{draft().sections[el.dataset.i][el.dataset.k]=el.value;saveLocal();showReader();});holder.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{draft().sections.splice(b.dataset.remove,1);renderSectionEditor();saveLocal();showReader();});}
$('loginForm').onsubmit=async e=>{e.preventDefault();try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('password').value})});const data=await r.json();if(!r.ok)throw Error();sessionStorage.setItem('vault-token',data.token);$('lock').hidden=true;await loadCloud();showDashboard();}catch{$('loginError').textContent='Incorrect password or server not configured.';}};
['titleInput','sectionInput','notesInput','factsInput'].forEach(id=>$(id).oninput=()=>{const d=draft();d.title=$('titleInput').value;d.section=$('sectionInput').value;d.notes=$('notesInput').value;d.facts=$('factsInput').value.split('\n').map(x=>x.trim()).filter(Boolean);saveLocal();showReader();});
$('imageInput').onchange=e=>{[...e.target.files].forEach(f=>{const r=new FileReader();r.onload=()=>{draft().images.push(r.result);saveLocal();showReader();};r.readAsDataURL(f);});e.target.value='';};$('addSection').onclick=()=>{draft().sections.push({heading:'New note section',notes:''});renderSectionEditor();saveLocal();};$('saveNow').onclick=saveCloud;$('editBtn').onclick=showEditor;$('closeEdit').onclick=showReader;$('libraryBtn').onclick=showDashboard;$('backBtn').onclick=showDashboard;$('lessonSelect').onchange=e=>{activeLesson=e.target.value;showReader();};$('newLessonBtn').onclick=()=>{const l=prompt('Lesson name');if(l?.trim()){library[activeSubject][l.trim()]??=blank(activeSubject,l.trim());activeLesson=l.trim();saveLocal();showReader();}};$('themeBtn').onclick=()=>document.body.classList.toggle('dark');$('printBtn').onclick=()=>window.print();seed();if(sessionStorage.getItem('vault-token')){$('lock').hidden=true;loadCloud().then(showDashboard);}
